CREATE TYPE "ProductType" AS ENUM ('PHYSICAL', 'SERVICE');

ALTER TABLE "Product"
ADD COLUMN "images" JSONB,
ADD COLUMN "salePrice" DECIMAL(12,2) NOT NULL DEFAULT 0.00,
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "brand" TEXT,
ADD COLUMN "trackStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0.00,
ADD COLUMN "minStock" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "productType" "ProductType" NOT NULL DEFAULT 'PHYSICAL',
ADD COLUMN "visibleInPos" BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX "Product_tenantId_isActive_idx" ON "Product"("tenantId", "isActive");
